version: 0.1.{build}
image: Visual Studio 2017

environment:
  docker_username:
    secure: b2cKuN3mLck9vm84qOfC9g==
  docker_password:
    secure: zK3mBk7glxDZuCKBHGINOQ1BRWJiaOUA+3bEWjT1Bk/QPfz/jWVQF6IS/n5KuoVe
  docker_organization:
    secure: O31RyxMbW2kjUIZnmwAlI1VZ2ARwMDjWeolUMCT+nTM=
  docker_repository:
    secure: O31RyxMbW2kjUIZnmwAlIyGjRR7WCzzvWxCs9kL8mrg=
  license_url:
    secure: niAprUCDiG+obOLNs9BnCEaFLb3zIrGVzqg2Xn6NxudI7DoleHWlDhK6a69722jpUy1cby3iqb7hhgtG54TQLsc0DpvSPSklZ6GUBLUcSXPeM2a0aRVG5dC2nlEl/4Pxo2817iQM8uMuLm1l43KtNM5gZxHFEkNZyWjIyJjYiAG6D+4jb1r3VkXLMfJXv6j1J3j74cGFY684FwZlB3bFkW0Y4kafbOvc5gJlQMNZUddxU3K9rt1Dc5KIZEGg4oPpAfAJA0ivYWGFNWfQJujeXw==
  sitecore_username:
    secure: uLbUPi0gLKEHi8f75ysLMczdR6Sl0oU025K59LRfM6o=
  sitecore_password:
    secure: e2aVeCR2p5UABsfJT0sS1A==

cache:
  - resourcefiles/ -> appveyor.yml

install:
  - ps: .\About.ps1
  - ps: |
      $env:docker_password | docker login --username $env:docker_username --password-stdin $env:docker_organization
      .\Install.ps1 -SitecoreUsername $env:sitecore_username -SitecorePassword $env:sitecore_password
      # only here in leiu of placing the license file in the directory ourself
      $resx = ".\resourcefiles"
      If (!(Test-Path "${resx}\license.xml")) {
        If (!(Test-Path $resx)) {
          New-Item $resx -ItemType Directory | Out-Null
        }
        Write-Output "Downloading license"
        Invoke-WebRequest $env:license_url -OutFile "${resx}\license.xml"
      }

build_script:
  - ps: |
      .\BuildSource.ps1
      .\BuildAll.ps1 -Repository $env:docker_repository -Publish