[CmdletBinding()]
Param(
  [Parameter()]
  [string]$Repository = "asif"
)
$ErrorActionPreference = "Stop"

$src = Join-Path $PSScriptRoot -ChildPath "src"
$dist = Join-Path $PSScriptRoot -ChildPath "resourcefiles"
$output = Join-Path $dist -ChildPath "SIF.Extension.ASIF.ps1"

Write-Output "Cleaning ${dist}"
If (Test-Path $dist) {
  Remove-item $dist -Recurse
}
New-Item $dist -ItemType Directory | Out-Null

Get-ChildItem $src -Include "*.json" -Recurse | Copy-Item -Destination $dist

"#`n# Auto-generated by build, do not modify this file directly.`n#" | Set-Content $output
Get-ChildItem $src -Include "*.ps1" -Exclude "*.Tests.ps1" -Recurse | ForEach-Object {
  $script = $_.FullName
  $scriptName = $_.Name

  Write-Output "Analyzing ${scriptName}"
  $analysis = Invoke-ScriptAnalyzer $script -Severity Error -Fix
  Get-ScriptAnalyzerRule | ForEach-Object {
    $ruleName = $_
    
    If ($analysis.RuleName -contains $ruleName) {
      $analysis | Where-Object "RuleName" -EQ $ruleName -OutVariable "failures" | Out-Default
      If ($failures.Count) {
        Write-Warning "${ruleName} has $($failures.Count) failures."
      }
    }
  }

  "<# ${scriptName} #>" | Add-Content $output
  Get-Content $script | Add-Content $output
}

@(
  @{
    Base = "microsoft/aspnet:4.6.2"
    Tag = @("sc90u2-aspnet4.6.2", "latest")
  }
  <#@{
    Base = "microsoft/aspnet:4.7"
    Tag = @("sc90u2-aspnet4.7")
  }
  @{
    Base = "microsoft/aspnet:4.7.1"
    Tag = @("sc90u2-aspnet4.7.1")
  }
  @{
    Base = "microsoft/aspnet:4.7.2"
    Tag = @("sc90u2-aspnet4.7.2", "latest")
  }#>
) | ForEach-Object {
  $base = $_.Base
  $tag = $_.Tag

  $buildArgs = @("build", "--build-arg", "BASEIMAGE=${base}")
  $tag | ForEach-Object { $buildArgs += @("--tag", "${Repository}:${_}") }
  $buildArgs += "."

  Write-Output "Building ${Repository}:${tag} atop ${base}"
  & docker $buildArgs
  If ($LASTEXITCODE) {
    Write-Error "Non-zero exit code ${LASTEXITCODE} while building ${tag}"
  }
}

Write-Output "Build complete."